#!/usr/bin/env php

<?php

include __DIR__ . "/../vendor/autoload.php";

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

// use Core\Conversor\;
include __DIR__ . "/conversor.php";

(new Application('convert', '0.0.1@baby'))
    ->register('convert')
    ->setDescription('Convert the \'encode\' of one project to UNICODE.')
    ->addArgument(
        'conversivel',
        InputArgument::IS_ARRAY | InputArgument::REQUIRED,
        "Indica quem sera convertido code|database"
    )->addOption(
        'input-path', null,
        InputOption::VALUE_OPTIONAL,
        'Path with projetcto to convert'
    )->addOption(
        'output-path', null,
        InputOption::VALUE_OPTIONAL,
        'Path for output converted project'
    )->addOption(
        'host', null,
        InputOption::VALUE_OPTIONAL,
        'Host to database instance',
        'localhost'
    )->addOption(
        'port', null,
        InputOption::VALUE_OPTIONAL,
        'Database port',
        '11001'
    )->addOption(
        'username', null,
        InputOption::VALUE_OPTIONAL,
        'Database username',
        'root'
    )->addOption(
        'password', null,
        InputOption::VALUE_OPTIONAL,
        'Password',
        'root'
    )->addOption(
        'database-name', null,
        InputOption::VALUE_OPTIONAL,
        'Database name',
        'syscor'
    )->addOption(
        'encode-type', null,
        InputOption::VALUE_OPTIONAL,
        'Encode-type',
        'utf-8'
    )
    ->setCode(function(InputInterface $input, OutputInterface $output) {

        $io = new SymfonyStyle($input, $output);

        $gabrieleAmorth = new Padre([
            'io'            => $io,
            'input_path'    => $input->getOption("input-path"),
            'output_path'   => $input->getOption("output-path"),
            'host'          => $input->getOption("host"),
            'port'          => $input->getOption("port"),
            'user_name'     => $input->getOption("username"),
            'password'      => $input->getOption("password"),
            'dbname'        => $input->getOption("database-name"),
            'encode_type'   => $input->getOption("encode-type"),
            'conversivel'   => $input->getArgument("conversivel")
        ]);

        $gabrieleAmorth->converter(); // Ayo Wololooo, Wololooo...!!!
    })
    ->getApplication()
    ->setDefaultCommand('convert', true)
    ->run();
